apiVersion: v1
kind: Service
metadata:
  name: garageos-api
  namespace: garageos
spec:
  # NodePort: expoe a API em http://localhost:30080 no Docker Desktop
  type: NodePort
  selector:
    app: garageos-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      name: http
