apiVersion: v1
kind: ConfigMap
metadata:
  name: garageos-config
  namespace: garageos
data:
  # Configuracoes nao-sensiveis da API
  ASPNETCORE_ENVIRONMENT: "Development"
  Jwt__Issuer: "GarageOS.Api"
  Jwt__Audience: "GarageOS.Client"
  Admin__Username: "admin"
  # Configuracoes nao-sensiveis do Postgres
  POSTGRES_USER: "garageos"
  POSTGRES_DB: "garageos"
