apiVersion: v1
kind: Secret
metadata:
  name: garageos-secret
  namespace: garageos
type: Opaque
# Valores em base64. Para decodificar/gerar:
#   echo -n 'valor' | base64
data:
  # POSTGRES_PASSWORD = garageos@123
  POSTGRES_PASSWORD: Z2FyYWdlb3NAMTIz
  # Jwt__SecretKey = GarageOS@SuperSecretKey#2026!XpTo
  Jwt__SecretKey: R2FyYWdlT1NAU3VwZXJTZWNyZXRLZXkjMjAyNiFYcFRv
  # Admin__Password = admin@123
  Admin__Password: YWRtaW5AMTIz
  # ConnectionStrings__DefaultConnection =
  #   Host=garageos-postgres;Port=5432;Database=garageos;Username=garageos;Password=garageos@123
  ConnectionStrings__DefaultConnection: SG9zdD1nYXJhZ2Vvcy1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9Z2FyYWdlb3M7VXNlcm5hbWU9Z2FyYWdlb3M7UGFzc3dvcmQ9Z2FyYWdlb3NAMTIz
