apiVersion: v1
kind: Service
metadata:
  name: garageos-postgres
  namespace: garageos
spec:
  # ClusterIP: acessivel apenas internamente no cluster
  type: ClusterIP
  selector:
    app: garageos-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
